#!/usr/bin/env node
/**
 * Build-time step: embed SKILL.md into a TypeScript module so the
 * `demath skill` subcommand can print the full skill file without
 * touching the filesystem at runtime.
 *
 * Runs as a `prebuild` hook (see package.json scripts). Regenerates
 * `src/skillContent.generated.ts` from `SKILL.md` so the bundled CLI
 * ships the skill inline; `npm install -g @demath-ai/cli` + `demath
 * skill` is sufficient for an AI agent to acquire the protocol's
 * agent-facing intro without hitting the network.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');
const sourcePath = resolve(repoRoot, 'SKILL.md');
const targetPath = resolve(repoRoot, 'src', 'skillContent.generated.ts');

let content;
try {
  content = readFileSync(sourcePath, 'utf8');
} catch (err) {
  console.error(`[embed-skill] could not read ${sourcePath}: ${err.message}`);
  process.exit(1);
}

mkdirSync(dirname(targetPath), { recursive: true });

const header = `// AUTO-GENERATED by scripts/embed-skill.mjs — DO NOT EDIT.
// Source: SKILL.md at the package root. Regenerated on every \`npm run build\`.\n`;

writeFileSync(
  targetPath,
  `${header}\nexport const SKILL_MD_CONTENT = ${JSON.stringify(content)};\n`,
  'utf8',
);

console.log(
  `[embed-skill] wrote ${targetPath} (${content.length.toLocaleString()} chars from SKILL.md)`,
);
